# Generated by Django 4.2.20 on 2025-04-28 20:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="BookStore",
            fields=[
                ("id", models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name="ID"
                )),
                ("title", models.CharField(max_length=256)),
                ("author", models.CharField(max_length=256)),
                ("record_dttm", models.DateTimeField(auto_now_add=True)),
                ("price", models.PositiveIntegerField()),
            ],
        ),
    ]
