# Generated by Django 4.2.20 on 2025-04-28 20:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookstore",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
