# Generated by Django 4.2.20 on 2025-04-28 20:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0002_bookstore_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookstore",
            name="quantity",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="bookstore",
            name="price",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
