# Generated by Django 4.2.20 on 2025-04-28 20:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0003_bookstore_quantity_alter_bookstore_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookstore",
            name="release_dt",
            field=models.DateField(null=True),
        ),
    ]
